version: '1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: tcc-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: tcc-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: tcc-kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  consumer:
    image: marcal/consumer
    container_name: marcal-consumer
    environment:
      KAFKA_BROKERS: tcc-kafka:9092
      CLOUD: teste123
    depends_on:
      - zookeeper
      - kafka
  publisher:
    image: marcal/publisher
    container_name: marcal-publisher
    ports:
      - "3333:3333"
    environment:
      KAFKA_BROKERS: tcc-kafka:9092
    depends_on:
      - zookeeper
      - kafka